### ISSUE TITLE
orbslam_dwo

### ISSUE THREAD

**Issue by weiweiyixin** [JzHuai0108/vio_g2o#2]
Hello!I followed you steps ,but a mistake is happened when run the porject.
test_orbslam: /usr/local/include/eigen3/Eigen/src/Core/DenseStorage.h:130：Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = double; int Size = 4; int MatrixOrArrayOptions = 0]: 假设 ‘(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"’ 失败。
Could please hlep me to solve this probleam?Thank you !

**Comment by JzHuai0108** [comment]
The error is largely caused by dynamically allocating instances of classes that have a Eigen object member. For instance, class Frame has at least a Sophus::SE3d object which is an Eigen object aggregate, and Frame has been allocated on the heap many times by Frame * aframe = new Frame().

The solution is to "put a EIGEN_MAKE_ALIGNED_OPERATOR_NEW macro in a public part " of such a class as discussed in http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html. 

I will fix this issue if I got extra time.

**Comment by weiweiyixin** [comment]
Thank you for your reply!I will try it!

**Comment by weiweiyixin** [comment]
I have tried it,but it didn't work.I want know what is "the public part"your said?Thanks!

**Comment by JzHuai0108** [comment]
The public part is shown below.


class A {

 public:

  // this is the public part, put eigen_new_operator macro here.

  int a;

 private:

  int z;

}


Meanwhile, I will fix the issue in a couple of days.

________________________________
